# Generated by Django 5.1.5 on 2026-01-28 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_status_alter_invoice_id_alter_invoiceitem_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='status',
        ),
    ]
