# Generated by Django 5.1.5 on 2026-01-28 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0003_remove_invoice_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('original_invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archived_record', to='invoices.invoice')),
            ],
            options={
                'verbose_name': 'فاتورة مؤرشفة',
                'verbose_name_plural': 'فواتير مؤرشفة',
                'ordering': ['-archived_at'],
            },
        ),
    ]
