# Generated by Django 5.1.5 on 2026-01-25 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ProductPriceTier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('wholesale', 'سعر الجملة'), ('wholesale_for_quantity', 'سعر الجملة للكمية'), ('quantity_price', 'سعر الكمية')], max_length=32)),
                ('min_quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='products.product')),
            ],
            options={
                'unique_together': {('product', 'key')},
            },
        ),
    ]
